/* tslint:disable */
/* eslint-disable */
/**
 * Fund Service API
 * API for managing fund transactions and balance overview for the authenticated user.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

