openapi: 3.0.0
info:
  title: Fund Service API
  version: 1.0.1
  description: API for managing fund transactions and balance overview for the authenticated user.
servers:
  - url: http://localhost:3002/funds
    description: Local development server
tags:
  - name: Fund Service
    description: Operations related to deposits, withdrawals, and fund overview.

paths:
  /funds/transactions:
    post:
      summary: Create a deposit or withdrawal transaction
      operationId: createTransaction
      tags:
        - Fund Service
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - type
                - amount
              properties:
                type:
                  type: string
                  enum: [deposit, withdrawal]
                  example: deposit
                amount:
                  type: number
                  format: float
                  example: 1000.00
                description:
                  type: string
                  example: "Monthly savings deposit"
      responses:
        '201':
          description: Transaction created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: string
                    example: tx789
                  userId:
                    type: number
                    
                    example: 123
                  type:
                    type: string
                    enum: [deposit, withdrawal]
                    example: deposit
                  amount:
                    type: number
                    format: float
                    example: 1000.00
                  description:
                    type: string
                    example: "Monthly savings deposit"
                  date:
                    type: string
                    format: date-time
                    example: 2025-07-09T17:30:00Z
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '404': { $ref: '#/components/responses/NotFound' }
        '500': { $ref: '#/components/responses/InternalServerError' }

  /funds/overview:
    get:
      summary: Retrieve balance and recent transactions for the authenticated user
      operationId: getFundsOverview
      tags:
        - Fund Service
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Funds overview retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: number
                    format: float
                    example: 5000.75
                  transactions:
                    type: array
                    items:
                      type: object
                      properties:
                        transactionId:
                          type: string
                          example: tx123
                        type:
                          type: string
                          enum: [deposit, withdrawal]
                          example: withdrawal
                        amount:
                          type: number
                          format: float
                          example: 250.00
                        date:
                          type: string
                          format: date-time
                          example: 2025-07-05T14:00:00Z
                        description:
                          type: string
                          example: "ATM withdrawal"
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '404': { $ref: '#/components/responses/NotFound' }
        '500': { $ref: '#/components/responses/InternalServerError' }

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          example: 400
        message:
          type: string
          example: Invalid request
        details:
          type: string
          nullable: true
          example: Type must be deposit or withdrawal

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: 400
            message: Invalid request data
            details: Amount must be a positive number

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: 401
            message: Unauthorized
            details: Missing or invalid authentication token

    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: 404
            message: Not Found
            details: No user account or transaction history found

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: 500
            message: Internal server error
            details: An unexpected error occurred on the server
