openapi: 3.0.0
info:
  title: Order Management Service API
  version: 1.0.0
  description: API for managing buy/sell orders and order history.
servers:
  - url: http://localhost:3001/orders
    description: Local development server
tags:
  - name: Order Management
    description: Operations related to placing, updating, and tracking orders

paths:
  /buy:
    post:
      summary: Place a buy order
      operationId: placeBuyOrder
      tags:
        - Order Management
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - stockSymbol
                - quantity
                - price
              properties:
                userId:
                  type: string
                  
                stockSymbol:
                  type: string
                quantity:
                  type: integer
                price:
                  type: number
      responses:
        '201':
          description: Buy order placed successfully
        '400':
          description: Invalid request data
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /sell:
    post:
      summary: Place a sell order
      operationId: placeSellOrder
      tags:
        - Order Management
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - stockSymbol
                - quantity
                - price
              properties:
                userId:
                  type: string
                stockSymbol:
                  type: string
                quantity:
                  type: integer
                price:
                  type: number
      responses:
        '201':
          description: Sell order placed successfully
        '400':
          description: Invalid request data
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /orders/{orderId}:
    put:
      summary: Update an existing order
      operationId: updateOrder
      tags:
        - Order Management
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                price:
                  type: number
      responses:
        '200':
          description: Order updated successfully
        '400':
          description: Invalid update data
        '401':
          description: Unauthorized
        '404':
          description: Order not found
        '500':
          description: Internal server error

    delete:
      summary: Cancel an order
      operationId: cancelOrder
      tags:
        - Order Management
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order cancelled successfully
        '401':
          description: Unauthorized
        '404':
          description: Order not found
        '500':
          description: Internal server error

    get:
      summary: Get details of a specific order
      operationId: getOrderDetails
      tags:
        - Order Management
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order details retrieved successfully
        '401':
          description: Unauthorized
        '404':
          description: Order not found
        '500':
          description: Internal server error

  /users/{userId}/orders:
    get:
      summary: Get all orders for a user
      operationId: getUserOrders
      tags:
        - Order Management
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of user orders retrieved successfully
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
