openapi: 3.0.0
info:
  title: Portfolio Management Service API
  version: 1.0.0
  description: API for managing user portfolios, transactions, and performance metrics.
servers:
  - url: http://localhost:3002/portfolio
    description: Local development server
tags:
  - name: Portfolio Management
    description: Operations related to tracking user portfolios and performance.
paths:
  /users/{userId}/portfolio:
    get:
      summary: Retrieve user's current portfolio
      operationId: getUserPortfolio
      tags:
        - Portfolio Management
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Portfolio retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  holdings:
                    type: array
                    items:
                      type: object
                      properties:
                        stockSymbol:
                          type: string
                          example: AAPL
                        quantity:
                          type: integer
                          example: 10
                        averagePrice:
                          type: number
                          format: float
                          example: 150.75
        '400':
          description: Invalid user ID format
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Internal server error

  /users/{userId}/transactions:
    get:
      summary: Retrieve transaction history for a user
      operationId: getUserTransactions
      tags:
        - Portfolio Management
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Transaction history retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    transactionId:
                      type: string
                      example: tx123
                    stockSymbol:
                      type: string
                      example: TSLA
                    type:
                      type: string
                      enum: [buy, sell]
                      example: buy
                    quantity:
                      type: integer
                      example: 5
                    price:
                      type: number
                      format: float
                      example: 720.5
                    date:
                      type: string
                      format: date-time
                      example: 2023-07-01T14:23:00Z
        '400':
          description: Invalid user ID
        '401':
          description: Unauthorized
        '404':
          description: User or transactions not found
        '500':
          description: Internal server error

  /users/{userId}/performance:
    get:
      summary: Retrieve portfolio performance metrics
      operationId: getUserPerformance
      tags:
        - Portfolio Management
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Performance metrics retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalValue:
                    type: number
                    format: float
                    example: 10250.75
                  totalInvested:
                    type: number
                    format: float
                    example: 9500.00
                  profitLoss:
                    type: number
                    format: float
                    example: 750.75
                  returnPercentage:
                    type: number
                    format: float
                    example: 7.9
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
